---
- name: Create TestContainer 
  hosts: cinraw
  become: yes
  remote_user: docker
  roles:
    - dockercentos7

- name: Install LAMP on TestContainer 
  hosts: testcontainer
  connection: docker
  remote_user: root
  become: yes
  vars_files:
    - host_vars/staging.yml
  roles:
    - common
    - httpd
    - git
    - php
    - mysql
    - redis

