---

- name: add repo
  command: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm creates=/etc/yum.repos.d/mysql-community.repo

- name: install mysql-community-server
  yum: name=mysql-community-server state=installed

- name: install MySQL-python for ansible mysql_user module
  yum: name=MySQL-python state=installed

- name: start server
  service: name=mysqld state=started enabled=yes
