---

- name: Install php repos
  yum: name={{ item }}
  with_items: 
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    - https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm

- name: Install php 7.1
  yum: name={{ item }} state=present enablerepo=ius
  with_items: 
    - mod_php71u  
    - php71u-mbstring
    - php71u-mysqlnd
    - php71u-pdo
    - php71u-gd
    - php71u-opcache
    - php71u-common
    - php71u-cli
    - php71u-mcrypt
  notify: restart httpd
  tags: [php]
